M48
; DRILL file {KiCad 7.0.10} date 西元2024年05月18日 (週六) 19時18分13秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-18T19:18:13+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.2677Y-2.0866
X3.2677Y-3.8189
X6.9685Y-2.0866
X6.9685Y-3.8189
M30
