// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Compass struct {
	HasCalibrated bool    `json:"hasCalibrated"`
	MagAzimuth    float64 `json:"magAzimuth"`
	Declination   float64 `json:"declination"`
}

type Mutation struct {
}

type PanTilt struct {
	IsBusy       bool `json:"isBusy"`
	HasFindNorth bool `json:"hasFindNorth"`
}

type Query struct {
}

type Station struct {
	Name          string  `json:"name"`
	Remark        string  `json:"remark"`
	Location      string  `json:"location"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	Altitude      float64 `json:"altitude"`
	Satellites    int     `json:"satellites"`
	PendingTasks  int     `json:"pendingTasks"`
	TaskCountdown int     `json:"taskCountdown"`
}

type System struct {
	Uptime    int      `json:"uptime"`
	CPUUsage  float64  `json:"cpuUsage"`
	MemUsage  float64  `json:"memUsage"`
	DiskUsage float64  `json:"diskUsage"`
	Release   string   `json:"release"`
	Arch      string   `json:"arch"`
	Hostname  string   `json:"hostname"`
	IP        []string `json:"ip"`
}

type TLEData struct {
	ID         int    `json:"id"`
	Name       string `json:"name"`
	Line1      string `json:"line_1"`
	Line2      string `json:"line_2"`
	Expired    bool   `json:"expired"`
	LastUpdate int    `json:"lastUpdate"`
}
