// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PanTilt struct {
	CurrentPan  float64 `json:"currentPan"`
	CurrentTilt float64 `json:"currentTilt"`
	NorthOffset float64 `json:"northOffset"`
}

type Query struct {
}

type Station struct {
	Name          string  `json:"name"`
	Remark        string  `json:"remark"`
	Location      string  `json:"location"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	Altitude      float64 `json:"altitude"`
	Satellites    int     `json:"satellites"`
	PendingTasks  int     `json:"pendingTasks"`
	TaskCountdown int     `json:"taskCountdown"`
}

type System struct {
	Uptime    int      `json:"uptime"`
	CPUUsage  float64  `json:"cpuUsage"`
	MemUsage  float64  `json:"memUsage"`
	DiskUsage float64  `json:"diskUsage"`
	Release   string   `json:"release"`
	Arch      string   `json:"arch"`
	Hostname  string   `json:"hostname"`
	IP        []string `json:"ip"`
}

type TLEData struct {
	ID            int    `json:"id"`
	Name          string `json:"name"`
	Line1         string `json:"line_1"`
	Line2         string `json:"line_2"`
	Expired       bool   `json:"expired"`
	LastUpdate    int    `json:"lastUpdate"`
	Geostationary bool   `json:"geostationary"`
}
