M48
; DRILL file {KiCad 7.0.10} date 西元2024年05月10日 (週五) 14時16分30秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-10T14:16:30+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.6811Y-1.9134
X2.6811Y-4.5039
X7.3583Y-1.9134
X7.3583Y-4.5039
M30
